[template]
src = "nginx.conf.tmpl"
dest = "/usr/local/nginx/conf/nginx.conf"
keys = [
    "/nginx/conf",
]
#check_cmd = "/usr/local/nginx/sbin/nginx -t -c {{.src}}"
#reload_cmd = "/usr/local/nginx/sbin/nginx -s reload"